### ISSUE TITLE
A na Nukkit działa?

### ISSUE THREAD

**Issue by TechAdrianPro** [Verciak/Vertty_AntyLogout#1]
A działa na Nukkit?

**Comment by Verciak** [comment]
> A działa na Nukkit?

Nie ma problemu abym to przepisał na nukkita za drobną opłatą.

**Comment by TechAdrianPro** [comment]
No to dobrze a za ile

**Comment by Verciak** [comment]
Verciak#1714 tu pisz

wt., 4 kwi 2023 o 15:20 TechAdrianPro ***@***.***> napisał(a):
